version: '3.9'

services:
  web:
    build: .
    command: ["dockerize", "-wait", "tcp://db:5432", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./env.dev
    networks:
      - backend  
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=bookstore_db
    networks:
      - backend

networks:
  backend:
    driver: bridge            

volumes:
  postgres_data:
