[tool.poetry]
name = "bookstore"
version = "0.1.0"
description = ""
authors = ["Rafael Almeida <dealmeida.silva@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1"
django-rest-framework = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
